Add ability to inject kwargs for Django Ninja Router
hbakri/django-ninja-crud pull request #93
Opened 2023-07-28 20:37 UTC by lucasrcezimbra

This PR enables the users to pass kwargs like `exclude_none`, `excluded_unset`, [etc](https://django-ninja.rest-framework.com/reference/operations-parameters/). to the Django Ninja Router.

2023-07-29 16:39 UTC, hbakri requested changes
Hi @lucasrcezimbra !

Firstly, I want to express my **sincere gratitude** for your interest in `django-ninja-crud` and for your valuable contribution. Having your fresh perspective on this feature is incredibly helpful and I'm really impressed with your approach to testing each `AbstractModelView` class directly. It's a fantastic addition to our test coverage!

I've reviewed your PR and overall it's excellent. However, I do have a few minor feedback points I'd like to share, and I hope we can work together to address these:

- **Test file location and naming**: For maintaining the consistency of our test structure, could you please move the test files related to views into a "tests/views" directory? Also, the file names would be more informative if they reflect what they're testing. For instance, tests for `CreateModelView` could be in a file named "test_create.py".
- **Test class naming convention**: In this project, I've been using the convention of adding "Test" as a suffix to the test classes (for example, `CreateModelViewTest`). Could we please update your new test classes to follow this convention?
- **Assertions in tests**: For the lines like: 
```python
router_mock.post.call_args[1]["exclude_none"] is True
```
I believe using an assertion like this: 
```python
self.assertIsTrue(router_mock.post.call_args[1]["exclude_none"])
``` 
would provide clearer intent and better error messaging if the test fails.
- **`router_kwargs` parameter**: I believe adding `router_kwargs` as a parameter in the `AbstractModelView` class could be beneficial as it's likely to be used by all subclasses. Here is a small snippet of what this could look like:
```python
class AbstractModelView:
    ...
    def __init__(..., router_kwargs: Optional[dict] = None):
        ...
        self.router_kwargs = router_kwargs or {}
    ...
```
Once again, I appreciate your efforts and contribution. Please let me know your thoughts on these points and if you have any questions or need any assistance implementing these changes.

2023-07-31 14:07 UTC, lucasrcezimbra commented
> For maintaining the consistency of our test structure, could you please move the test files related to views into a "tests/views" directory?

You mean `tests/test_app/views`, `tests/views`, or `tests/test_app/tests/views`?

2023-07-31 14:31 UTC, lucasrcezimbra commented
I think I addressed all points. Thanks for the fast review. Let me know if you find any other improvements.

2023-07-31 14:40 UTC, hbakri reviewed
Thank you for the incredibly swift response and the work you've put into these changes! Everything looks almost perfect.

I've spotted a minor naming issue with the test classes, but it's a small detail. I'll point it out directly in the code using GitHub's line comment feature for a precise review.

Other than that, this is shaping up excellently. Once that little adjustment is made, I believe we'll be all set.

Again, great job, and I appreciate your collaboration on this!

2023-07-31 14:40 UTC, hbakri commented on tests/views/test_update.py
> +class UpdateModelViewSetTest(TestCase):
`UpdateModelViewTest`

2023-07-31 14:40 UTC, hbakri commented on tests/views/test_retrieve.py
> +class RetrieveModelViewSetTest(TestCase):
`RetrieveModelViewTest`

2023-07-31 14:40 UTC, hbakri commented on tests/views/test_patch.py
> +class UpdateModelViewSetTest(TestCase):
`PatchModelViewTest`

2023-07-31 14:40 UTC, hbakri commented on tests/views/test_list.py
> +class ListModelViewSetTest(TestCase):
`ListModelViewTest`

2023-07-31 14:40 UTC, hbakri commented on tests/views/test_delete.py
> +class DeleteModelViewSetTest(TestCase):
`DeleteModelViewTest`

2023-07-31 14:40 UTC, hbakri commented on tests/views/test_create.py
> +class CreateModelViewSetTest(TestCase):
`CreateModelViewTest`

2023-07-31 19:45 UTC, lucasrcezimbra commented on tests/views/test_update.py
> +class UpdateModelViewSetTest(TestCase):
```suggestion
class UpdateModelViewTest(TestCase):
```

2023-07-31 19:45 UTC, lucasrcezimbra commented on tests/views/test_retrieve.py
> +class RetrieveModelViewSetTest(TestCase):
```suggestion
class RetrieveModelViewTest(TestCase):
```

2023-07-31 19:45 UTC, lucasrcezimbra commented on tests/views/test_patch.py
> +class UpdateModelViewSetTest(TestCase):
```suggestion
class PatchModelViewTest(TestCase):
```

2023-07-31 19:45 UTC, lucasrcezimbra commented on tests/views/test_list.py
> +class ListModelViewSetTest(TestCase):
```suggestion
class ListModelViewTest(TestCase):
```

2023-07-31 19:45 UTC, lucasrcezimbra commented on tests/views/test_delete.py
> +class DeleteModelViewSetTest(TestCase):
```suggestion
class DeleteModelViewTest(TestCase):
```

2023-07-31 19:45 UTC, lucasrcezimbra commented on tests/views/test_create.py
> +class CreateModelViewSetTest(TestCase):
```suggestion
class CreateModelViewTest(TestCase):
```

2023-07-31 20:56 UTC, hbakri approved these changes

2023-07-31 20:57 UTC, merged